= Pflichtenheft FoodTable
// Metadata
:author: Eichhorn, Herzog, Wallinger
:email: info@foodtable.at
:date: 2020-01-19
:revision: 1.1
// Settings
:source-highlighter: coderay
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
// Refs:
// :imagesdir: images
// :sourcedir-code: src/main/java/at/htl/jdbcprimer
// :sourcedir-test: src/test/java/at/htl/jdbcprimer
:toc:

Version: {revision}

++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
++++

== Motivation
Als Bewohner eines Schülerwohnheims ist es mir wichtig zu wissen, welche Speisen es wann gibt. Mein Schülerheim bietet
keine Möglichkeit an, den Speiseplan über das Internet abzurufen. Mit diesem Projekt wollen wir ein Hilfsmittel zur einfachen Veröffentlichung erstellen.

== Ausgangszustand
Ausgegangen wird von einem Wohnheim im Zentralraum Linz - das Wohnheim richtet sich an Schüler und Lehrlinge.
Täglich werden Speisen (Frühstück und Abendessen) serviert.

== Istzustand
Der Speiseplan wird wöchentlich auf einem "schwarzen Brett" veröffentlicht.
Will ein Schüler sich unterwegs über den aktuellen Plan informieren muss er diesen vorher aufgeschrieben bzw. fotografiert haben.

=== Aktivitätsdiagramm Istzustand
[plantuml,activity,png]
....
@startuml
|Mitarbeiter|
start
:Plan erstellen;
    :Plan ausdrucken;
    :Plan aushängen;
|Bewohner|
if(Speiseplan fotografiert?     ) then (Ja)
    else (Nein)
    :Speiseplan fotografieren;
endif
:Foto zugreifen;
stop
@enduml
....


== Problemstellung
In fast allen Wohnheimen ist der (oftmals wöchentliche) Speiseplan nur offline verfügbar - aus diesem Grund fotografieren sich die Bewohner den Speiseplan einfach.
Ärgerlich ist es besonders dann, wenn man vergessen hat, sich den Plan zu fotografieren.

== Aufgabenstellung
Es ist eine Android-App zu einer dazugehörigen Webanwendung (https://dev.foodtable.at) zu erstellen, die es ermöglicht,
die Daten einfach und schnell mithilfe eines QR-Codes abzurufen. Eine denkbare Erweiterung wäre die Implementierung einer
Benachrichtigungsfunktion (Pushnachricht an Android-Smartphones), um Bewohner über Neuigkeiten zu informieren.

=== Klassendiagramm
[plantuml,class,png]
....
@startuml
left to right direction
class Mitarbeiter {
    Name
    E-Mail
    WH-Zuweisung
    verwaltePlan()
    verwalteWH()
}
class Bewohner {
    WH-Zuweisung
    tätigeEinsichtnahme()
}

class Wohnheim {
    WH-Code
    Name
    Anschrift
    neusterSpeiseplan()
}

class Speiseplan {
    KW
    Wohnheim
    Speisen
    Allergene
}
Wohnheim"1" -- "*"Bewohner: wohnt in <
Mitarbeiter"*" -- "1"Wohnheim : arbeitet in >


Wohnheim  "1" -- "*"Speiseplan : gehört zu <

@enduml
....

=== Anwendungsfalldiagramm
[plantuml,use-case,png]
....
@startuml
left to right direction
actor Mitarbeiter
actor Bewohner
rectangle FoodTable {
  Mitarbeiter -- (Einsicht)
  Mitarbeiter -- (Speiseplanverwaltung)
  (Speiseplanverwaltung) .> (Einsicht) : include
  (Einsicht) -- Bewohner
}
@enduml
....


=== Aktivitätsdiagramm Sollzustand
[plantuml,activity2,png]
....
@startuml
|Mitarbeiter|
start
:Plan erstellen;
:Speiseplan online eingeben;
|Bewohner|
:Scanne QR-Code in App  ;
:Informationen lesen ;
stop
@enduml
....



== Zielsetzung
Ziel des Projekts ist es, den Speiseplan eines Wohnheims einfacher und schneller über das Internet abrufbar
zu machen. Die Wohnheimverwaltung sollte sich möglichst schnell im Webinterface zurechtfinden können,
selbiges gilt für die Bewohner (beim Verwenden der App oder der Website im abgemeldeten Zustand).

== Funktionale Anforderungen
* Speiseplan online einsehbar
* Allergene zu Speisen anzeigen
* Essen zu verschiedenen Zeiten anzeigen (Früh, Mittag, Abend)
* Benachrichtigungsfunktion

== Nichtfunktionale Anforderungen
* Datensicherheit & Datenschutz (Accountdaten, Login/Registrierung, ...)
* Zuverlässigkeit
* Effizienz

== Mengengerüst
Die Anzahl der vorrausichtlichen Benutzer lässt sich in diesem Fall nicht wirklich schätzen:
Pro Wohnheim gibt es im Grunde eine Person, die für das Eintragen des Speiseplans verantwortlich ist.
In Spezialfällen können einem Wohnheim mehrere Benutzerkonten zugewiesen werden.

Je nach Wohnheim kann Frühstück, Mittag- und Abendessen aktiviert oder deaktiviert werden.
Im Standardtemplate befinden sich in einer Woche also 3 (Anzahl Essenstypen) * 5 (Wochentage) * 2 (Doppelte Felder wg. Allergenen)
-> 30 Datenfelder pro Woche in einem Wohnheim.

Die Zugriffsrate kann ebenfalls nicht vorausgesagt werden: Je nach Anzahl der registrierten Wohnheime und Bewohner variiert diese stark.
